### ISSUE TITLE
Openmeta "failed to add"

### ISSUE THREAD

**Issue by henryjfry** [a4k-openproject/repository.openmeta#2]
Since I updated openmeta to version 1.1.3 I am getting the notification "Openmeta failed to add 12345" where 12345 is a placeholder for what seems like every TV show in my openmeta library integration folder. I've got a fair number of shows so the notification is up in the screen for a good while every reboot now.

I can turn on debug logging and see what the logs report but I'm fairly certain it's trying to add show folders which already exist because it's been updating my new episodes just fine.
Should I delete all the folders and let openmeta repopulate them to get rid of the error?

**Comment by SoulTV** [comment]
1.1.3 is not current. Update and see if that helps

**Comment by drinfernoo** [comment]
You're on an old version, and opened this issue in the wrong repository.

**Comment by henryjfry** [comment]
Yeah updating seemed to resolve it. Apologies, at the time I didn't see a new version and I didn't realise this was the wrong repo.

Cheers
