### ISSUE TITLE
Getting error on Tv Shows section Popular TMDB

### ISSUE THREAD

**Issue by xyzfre** [a4k-openproject/repository.openmeta#4]
Notice yesterday after the update and I tried on two different devices same error TV show section Popular (TMDB) loads for like a minute and no shows come up and then a OpenMeta error message pops up,, besides that every Other section works great love OpenMeta Thank you for all your hard work

**Comment by drinfernoo** [comment]
Can you provide a log? We would need to see the error in order to diagnose.

**Comment by xyzfre** [comment]
I’m at work right now when I get off I’ll duplicate the error and get you a log file Thank you for your response much appreciate it

**Comment by drinfernoo** [comment]
At that time, please open an issue at https://www.github.com/a4k-openproject/plugin.video.openmeta/issues/, so we can keep them all together 👍
